apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: defense-service
  name: defense-service
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: defense-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: defense-service
    spec:
      containers:
        - image: gcr.io/defense-api-300416/github.com/nadyasirimanna/defense-service
          imagePullPolicy: IfNotPresent
          name: defense-service-1
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: defense-service
  name: defense-service-hpa-isun
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: defense-service
